include = [
    "*.py",
    "cli"
]

exclude = [
    ".git",
    ".venv",
    ".antlr",
    "SixNF*.py"
]

line-length = 120
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
